language: cpp

# OS config, depends on actual 'os' in build matrix
dist: bionic

stages:
  - build

env:
  global:
    - SCONS_CACHE=$HOME/.scons_cache/$TRAVIS_BRANCH
    - SCONS_CACHE_LIMIT=1024
    - OPTIONS="debug_symbols=no verbose=yes progress=no"

cache:
  directories:
    - $SCONS_CACHE

matrix:
  include:
    - name: Android export template (release_debug, Clang)
      stage: build
      env: PLATFORM=android TOOLS=no TARGET=release_debug CACHE_NAME=${PLATFORM}-clang EXTRA_ARGS="warnings=extra werror=yes"
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - openjdk-8-jdk

# TODO: iOS MoltenVK support

#    - name: iOS export template (debug, Clang)
#      stage: build
#      env: PLATFORM=iphone TOOLS=no TARGET=debug CACHE_NAME=${PLATFORM}-clang
#      os: osx
#      osx_image: xcode11.5
#      compiler: clang
#      addons:
#        homebrew:
#          packages:
#            - scons

    - name: JavaScript export template (release, emscripten latest)
      stage: build
      env: PLATFORM=javascript TOOLS=no TARGET=release CACHE_NAME=${PLATFORM}-emcc-latest EXTRA_ARGS="use_closure_compiler=yes"
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *linux_deps

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.8 system;
      pip3 install --user scons;
    fi
  - scons --version
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PLATFORM" = "android" ]; then
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64;
      export PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:${PATH};
      java -version;
      misc/ci/android-tools-linux.sh;
    fi
  - if [ "$PLATFORM" = "javascript" ]; then
      git clone --depth 1 "https://github.com/emscripten-core/emsdk.git";
      ./emsdk/emsdk install latest;
      ./emsdk/emsdk activate --no-embedded latest;
    fi

before_script:
  - if [ "$PLATFORM" = "android" ]; then
      export ANDROID_HOME=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-sdk;
      export ANDROID_NDK_ROOT=$TRAVIS_BUILD_DIR/godot-dev/build-tools/android-ndk;
    fi

script:
  - scons -j2 CC=$CC CXX=$CXX platform=$PLATFORM tools=$TOOLS target=$TARGET $OPTIONS $EXTRA_ARGS
